
############## SONGS
POST http://localhost:5240/api/song HTTP/1.1
Content-Type: application/json

{
    "SongName": "Wake me up when September ends",
    "ArtistName": "Green Day",
    "Genre": "Rock"
}

###

GET http://localhost:5240/api/songs HTTP/1.1

###

GET http://localhost:5240/api/song/3 HTTP/1.1

###

DELETE http://localhost:5240/api/song/2 HTTP/1.1

###

PUT http://localhost:5240/api/song/4 HTTP/1.1
Content-Type: application/json

{
    "SongName": "Monsters",
    "ArtistName": "All Time Low",
    "Genre": "Rock"
}


########## USERS

POST http://localhost:5240/api/user HTTP/1.1
Content-Type: application/json

{
    "FirstName": "Löken",
    "LastName": "Lundahl",
    "Email": "robin.lundassssssssssshl@hssotma5sil.se",
    "PhoneNumber": "0702428ssssssssssssss4s265",
    "Password": "asdffdg234"
}

###

GET http://localhost:5240/api/user HTTP/1.1

###

GET http://localhost:5240/api/user/3fa85f64-5717-4562-b3fc-2c963f66afa6 HTTP/1.1

###

DELETE http://localhost:5240/api/user/23 HTTP/1.1

###

PUT http://localhost:5240/api/user/12 HTTP/1.1
Content-Type: application/json

{
    "FirstName": "Sandra",
    "LastName": "Lundahl",
    "Email": "robin.lundahl@hotmail.io",
    "PhoneNumber": "0702428424",
    "Password": "lalala"
}